USE ROLE SYSADMIN;

CREATE WAREHOUSE INGEST_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;


CREATE DATABASE RAW_DB;
CREATE DATABASE ANALYTICS_DB;

USE DATABASE RAW_DB;
CREATE SCHEMA POSTGRES;
CREATE SCHEMA GOOGLE_SHEETS;


USE ROLE SECURITYADMIN;

CREATE ROLE INGEST_ROLE;


GRANT USAGE ON WAREHOUSE INGEST_WH TO ROLE INGEST_ROLE;

GRANT USAGE ON DATABASE RAW_DB TO ROLE INGEST_ROLE;
GRANT USAGE ON SCHEMA RAW_DB.POSTGRES TO ROLE INGEST_ROLE;
GRANT USAGE ON SCHEMA RAW_DB.GOOGLE_SHEETS TO ROLE INGEST_ROLE;

GRANT  INSERT, SELECT
ON ALL TABLES IN SCHEMA RAW_DB.POSTGRES
TO ROLE INGEST_ROLE;



USE ROLE USERADMIN;
CREATE USER MELTANO_USER
PASSWORD = 'strong_password'
DEFAULT_ROLE = INGEST_ROLE
DEFAULT_WAREHOUSE = INGEST_WH
MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE INGEST_ROLE TO USER MELTANO_USER;





